from __future__ import annotations

from typing import Protocol

from domain.models import Project, Run, Team, AgentDefinition, WorkItem, WorkItemKind, WorkItemStatus


class ProjectStore(Protocol):
    def add(self, project: Project) -> Project: ...
    def get(self, project_id: str, owner_id: str) -> Project | None: ...
    def list(self, owner_id: str, limit: int = 50, offset: int = 0) -> list[Project]: ...
    def update(self, project: Project) -> Project: ...
    def delete(self, project_id: str, owner_id: str) -> bool: ...


class WorkItemStore(Protocol):
    def add(self, item: WorkItem) -> WorkItem: ...
    def get(self, item_id: str) -> WorkItem | None: ...
    def list(
        self,
        project_id: str,
        kind: WorkItemKind | None = None,
        status: WorkItemStatus | None = None,
        parent_id: str | None = None,
        limit: int = 100,
        offset: int = 0,
    ) -> list[WorkItem]: ...
    def update(self, item: WorkItem) -> WorkItem: ...
    def delete(self, item_id: str) -> bool: ...


class TeamStore(Protocol):
    def add(self, team: Team, agents: list[AgentDefinition]) -> Team: ...
    def get(self, team_id: str, owner_id: str) -> Team | None: ...
    def list(self, owner_id: str) -> list[Team]: ...
    def agents(self, team_id: str) -> list[AgentDefinition]: ...


class RunStore(Protocol):
    def add(self, run: Run) -> Run: ...
    def get(self, run_id: str) -> Run | None: ...
    def list_for_task(self, task_id: str) -> list[Run]: ...
    def update(self, run: Run) -> Run: ...
