"""Pure source-control naming/body policy. No I/O."""

# Workspace dirs yaah injects into every run worktree (Claude hook/settings + skills, the
# orchestration decision/verdict/outbox scratch, and `.yaah-eng/` — the nested per-engineer
# worktrees of a parallel wave). They must NOT land in the agent's commit/PR, so commit_all
# excludes them.
WORKSPACE_SCRATCH: tuple[str, ...] = (".claude", ".orchestration", ".yaah-eng")


def branch_name(task_id: str) -> str:
    return f"agent/{task_id}"


def commit_message(title: str) -> str:
    return f"{title}\n\nGenerated by a yaah run."


def pr_title(title: str) -> str:
    return f"[yaah] {title}"


def pr_body(title: str, body: str, acceptance_criteria: list[str]) -> str:
    lines = [body or "", "", "## Acceptance criteria"]
    lines += [f"- {c}" for c in acceptance_criteria]
    lines += ["", "_Generated by a yaah run._"]
    return "\n".join(lines)
