"""Pure source-control naming/body policy. No I/O."""


def branch_name(task_id: str) -> str:
    return f"agent/{task_id}"


def commit_message(title: str) -> str:
    return f"{title}\n\nGenerated by a yaah run."


def pr_title(title: str) -> str:
    return f"[yaah] {title}"


def pr_body(title: str, body: str, acceptance_criteria: list[str]) -> str:
    lines = [body or "", "", "## Acceptance criteria"]
    lines += [f"- {c}" for c in acceptance_criteria]
    lines += ["", "_Generated by a yaah run._"]
    return "\n".join(lines)
