from typing import Protocol


class StoragePort(Protocol):
    """Key/value-ish blob storage. Keys are relative paths like 'runs/{id}/plan.md'.
    LocalStorageAdapter backs this now; an S3 adapter can drop in later (A4)."""

    def write_bytes(self, key: str, content: bytes) -> None: ...
    def read_text(self, key: str, *, encoding: str = "utf-8") -> str: ...
    def exists(self, key: str) -> bool: ...
    def delete(self, key: str) -> None: ...
    def delete_directory(self, prefix: str) -> None: ...
    def local_path(self, key: str) -> str: ...
