from typing import Protocol


class StoragePort(Protocol):
    """Blob storage port. Keys are relative paths like 'runs/{id}/plan.md'.

    Co-located with its implementation in the adapters layer (same convention as
    adapters/database/ports.py). LocalStorageAdapter backs this now; an
    S3StorageAdapter can drop in later (A4) with no caller changes.
    """

    def write_bytes(self, key: str, content: bytes) -> None: ...
    def read_text(self, key: str, *, encoding: str = "utf-8") -> str: ...
    def read_bytes(self, key: str) -> bytes: ...
    def exists(self, key: str) -> bool: ...
    def delete(self, key: str) -> None: ...
    def delete_directory(self, prefix: str) -> None: ...
    def local_path(self, key: str) -> str: ...
